window.SONGMORE_CATALOG = [
  ["Blinding Lights", "The Weeknd"],
  ["Levitating", "Dua Lipa"],
  ["As It Was", "Harry Styles"],
  ["bad guy", "Billie Eilish"],
  ["Shape of You", "Ed Sheeran"],
  ["Heat Waves", "Glass Animals"],
  ["Anti-Hero", "Taylor Swift"],
  ["Cruel Summer", "Taylor Swift"],
  ["Flowers", "Miley Cyrus"],
  ["Sunflower", "Post Malone"],
  ["Someone You Loved", "Lewis Capaldi"],
  ["Uptown Funk", "Mark Ronson"],
  ["Rolling in the Deep", "Adele"],
  ["Take On Me", "a-ha"],
  ["Billie Jean", "Michael Jackson"],
  ["Smells Like Teen Spirit", "Nirvana"],
  ["Wonderwall", "Oasis"],
  ["Mr. Brightside", "The Killers"],
  ["Seven Nation Army", "The White Stripes"],
  ["Bohemian Rhapsody", "Queen"],
  ["Don't Stop Believin'", "Journey"],
  ["Lose Yourself", "Eminem"],
  ["HUMBLE.", "Kendrick Lamar"],
  ["One Dance", "Drake"],
  ["Stayin' Alive", "Bee Gees"],
  ["September", "Earth, Wind & Fire"],
  ["Superstition", "Stevie Wonder"],
  ["Crazy in Love", "Beyoncé"],
  ["Umbrella", "Rihanna"],
  ["Old Town Road", "Lil Nas X"],
  ["I Wanna Dance with Somebody", "Whitney Houston"],
  ["Somebody That I Used to Know", "Gotye"],
  ["Sweet Child O' Mine", "Guns N' Roses"],
  ["God's Plan", "Drake"],
  ["Dance Monkey", "Tones And I"],
  ["Watermelon Sugar", "Harry Styles"],
  ["Poker Face", "Lady Gaga"],
  ["good 4 u", "Olivia Rodrigo"],
  ["drivers license", "Olivia Rodrigo"],
  ["STAY", "The Kid LAROI"],
  ["Industry Baby", "Lil Nas X"],
  ["Peaches", "Justin Bieber"],
  ["Save Your Tears", "The Weeknd"],
  ["Die For You", "The Weeknd"],
  ["Starboy", "The Weeknd"],
  ["Can't Feel My Face", "The Weeknd"],
  ["One More Time", "Daft Punk"],
  ["Get Lucky", "Daft Punk"],
  ["Around the World", "Daft Punk"],
  ["Bad Habits", "Ed Sheeran"],
  ["Perfect", "Ed Sheeran"],
  ["Thinking Out Loud", "Ed Sheeran"],
  ["Shivers", "Ed Sheeran"],
  ["Easy On Me", "Adele"],
  ["Hello", "Adele"],
  ["Set Fire to the Rain", "Adele"],
  ["Someone Like You", "Adele"],
  ["Blank Space", "Taylor Swift"],
  ["Shake It Off", "Taylor Swift"],
  ["Love Story", "Taylor Swift"],
  ["You Belong With Me", "Taylor Swift"],
  ["Cardigan", "Taylor Swift"],
  ["Don't Start Now", "Dua Lipa"],
  ["New Rules", "Dua Lipa"],
  ["Physical", "Dua Lipa"],
  ["Houdini", "Dua Lipa"],
  ["vampire", "Olivia Rodrigo"],
  ["traitor", "Olivia Rodrigo"],
  ["happier", "Olivia Rodrigo"],
  ["Espresso", "Sabrina Carpenter"],
  ["Please Please Please", "Sabrina Carpenter"],
  ["Nonsense", "Sabrina Carpenter"],
  ["Paint The Town Red", "Doja Cat"],
  ["Kiss Me More", "Doja Cat"],
  ["Say So", "Doja Cat"],
  ["Woman", "Doja Cat"],
  ["BREAK MY SOUL", "Beyoncé"],
  ["CUFF IT", "Beyoncé"],
  ["Single Ladies (Put a Ring on It)", "Beyoncé"],
  ["Halo", "Beyoncé"],
  ["Formation", "Beyoncé"],
  ["HUMBLE.", "Kendrick Lamar"],
  ["Not Like Us", "Kendrick Lamar"],
  ["DNA.", "Kendrick Lamar"],
  ["Alright", "Kendrick Lamar"],
  ["SICKO MODE", "Travis Scott"],
  ["goosebumps", "Travis Scott"],
  ["FEIN", "Travis Scott"],
  ["Butterfly Effect", "Travis Scott"],
  ["Rockstar", "Post Malone"],
  ["Circles", "Post Malone"],
  ["Congratulations", "Post Malone"],
  ["Wow.", "Post Malone"],
  ["Lucid Dreams", "Juice WRLD"],
  ["All Girls Are The Same", "Juice WRLD"],
  ["Godzilla", "Eminem"],
  ["The Real Slim Shady", "Eminem"],
  ["Without Me", "Eminem"],
  ["Love The Way You Lie", "Eminem"],
  ["In Da Club", "50 Cent"],
  ["Candy Shop", "50 Cent"],
  ["Gold Digger", "Kanye West"],
  ["Stronger", "Kanye West"],
  ["Heartless", "Kanye West"],
  ["Power", "Kanye West"],
  ["Bound 2", "Kanye West"],
  ["Niggas In Paris", "Jay-Z"],
  ["Empire State of Mind", "Jay-Z"],
  ["99 Problems", "Jay-Z"],
  ["Hotline Bling", "Drake"],
  ["In My Feelings", "Drake"],
  ["Nice For What", "Drake"],
  ["Started From the Bottom", "Drake"],
  ["First Class", "Jack Harlow"],
  ["Whats Poppin", "Jack Harlow"],
  ["MONTERO (Call Me By Your Name)", "Lil Nas X"],
  ["INDUSTRY BABY", "Lil Nas X"],
  ["THATS WHAT I WANT", "Lil Nas X"],
  ["Mask Off", "Future"],
  ["Life Is Good", "Future"],
  ["Low", "Flo Rida"],
  ["Club Can't Handle Me", "Flo Rida"],
  ["SexyBack", "Justin Timberlake"],
  ["Can't Stop the Feeling!", "Justin Timberlake"],
  ["Cry Me a River", "Justin Timberlake"],
  ["Sorry", "Justin Bieber"],
  ["Love Yourself", "Justin Bieber"],
  ["Baby", "Justin Bieber"],
  ["Stay", "Rihanna"],
  ["Diamonds", "Rihanna"],
  ["Work", "Rihanna"],
  ["We Found Love", "Rihanna"],
  ["Only Girl (In the World)", "Rihanna"],
  ["Umbrella", "Rihanna"],
  ["WAP", "Cardi B"],
  ["Bodak Yellow", "Cardi B"],
  ["up", "Cardi B"],
  ["Super Bass", "Nicki Minaj"],
  ["Anaconda", "Nicki Minaj"],
  ["Starships", "Nicki Minaj"],
  ["Bang Bang", "Jessie J"],
  ["Price Tag", "Jessie J"],
  ["Call Me Maybe", "Carly Rae Jepsen"],
  ["I Really Like You", "Carly Rae Jepsen"],
  ["Royals", "Lorde"],
  ["Green Light", "Lorde"],
  ["Team", "Lorde"],
  ["Somebody That I Used to Know", "Gotye"],
  ["Somebody Told Me", "The Killers"],
  ["When You Were Young", "The Killers"],
  ["Use Somebody", "Kings of Leon"],
  ["Sex on Fire", "Kings of Leon"],
  ["Pumped Up Kicks", "Foster the People"],
  ["Electric Feel", "MGMT"],
  ["Kids", "MGMT"],
  ["Time to Pretend", "MGMT"],
  ["Feel Good Inc.", "Gorillaz"],
  ["Clint Eastwood", "Gorillaz"],
  ["DARE", "Gorillaz"],
  ["Feel It Still", "Portugal. The Man"],
  ["Shut Up and Dance", "WALK THE MOON"],
  ["Uptown Funk", "Bruno Mars"],
  ["24K Magic", "Bruno Mars"],
  ["That's What I Like", "Bruno Mars"],
  ["Locked Out of Heaven", "Bruno Mars"],
  ["Just the Way You Are", "Bruno Mars"],
  ["Grenade", "Bruno Mars"],
  ["Treasure", "Bruno Mars"],
  ["Finesse", "Bruno Mars"],
  ["Die With A Smile", "Lady Gaga"],
  ["Bad Romance", "Lady Gaga"],
  ["Paparazzi", "Lady Gaga"],
  ["Just Dance", "Lady Gaga"],
  ["Shallow", "Lady Gaga"],
  ["Born This Way", "Lady Gaga"],
  ["Telephone", "Lady Gaga"],
  ["Rain On Me", "Lady Gaga"],
  ["We Are Young", "fun."],
  ["Some Nights", "fun."],
  ["Viva La Vida", "Coldplay"],
  ["Yellow", "Coldplay"],
  ["The Scientist", "Coldplay"],
  ["Fix You", "Coldplay"],
  ["Clocks", "Coldplay"],
  ["A Sky Full of Stars", "Coldplay"],
  ["Hymn for the Weekend", "Coldplay"],
  ["Paradise", "Coldplay"],
  ["Radioactive", "Imagine Dragons"],
  ["Believer", "Imagine Dragons"],
  ["Demons", "Imagine Dragons"],
  ["Thunder", "Imagine Dragons"],
  ["Bones", "Imagine Dragons"],
  ["Counting Stars", "OneRepublic"],
  ["Apologize", "OneRepublic"],
  ["I Ain't Worried", "OneRepublic"],
  ["Secrets", "OneRepublic"],
  ["Wake Me Up", "Avicii"],
  ["Levels", "Avicii"],
  ["The Nights", "Avicii"],
  ["Hey Brother", "Avicii"],
  ["Titanium", "David Guetta"],
  ["Sexy Bitch", "David Guetta"],
  ["Memories", "David Guetta"],
  ["I'm Good (Blue)", "David Guetta"],
  ["Animals", "Martin Garrix"],
  ["Scared to Be Lonely", "Martin Garrix"],
  ["This Is What You Came For", "Calvin Harris"],
  ["Summer", "Calvin Harris"],
  ["Feel So Close", "Calvin Harris"],
  ["We Found Love", "Calvin Harris"],
  ["One Kiss", "Calvin Harris"],
  ["Outside", "Calvin Harris"],
  ["Lean On", "Major Lazer"],
  ["Cold Water", "Major Lazer"],
  ["Closer", "The Chainsmokers"],
  ["Something Just Like This", "The Chainsmokers"],
  ["Don't Let Me Down", "The Chainsmokers"],
  ["Paris", "The Chainsmokers"],
  ["Happier", "Marshmello"],
  ["Friends", "Marshmello"],
  ["Silence", "Marshmello"],
  ["Wolves", "Selena Gomez"],
  ["Lose You To Love Me", "Selena Gomez"],
  ["Good For You", "Selena Gomez"],
  ["Come & Get It", "Selena Gomez"],
  ["Calm Down", "Rema"],
  ["Love Me Like You Do", "Ellie Goulding"],
  ["Burn", "Ellie Goulding"],
  ["Lights", "Ellie Goulding"],
  ["Love Me Like You Do", "Ellie Goulding"],
  ["Chandelier", "Sia"],
  ["Cheap Thrills", "Sia"],
  ["Elastic Heart", "Sia"],
  ["Unstoppable", "Sia"],
  ["Royals", "Lorde"],
  ["Stitches", "Shawn Mendes"],
  ["Treat You Better", "Shawn Mendes"],
  ["There's Nothing Holdin' Me Back", "Shawn Mendes"],
  ["Señorita", "Shawn Mendes"],
  ["What Makes You Beautiful", "One Direction"],
  ["Night Changes", "One Direction"],
  ["Story of My Life", "One Direction"],
  ["Drag Me Down", "One Direction"],
  ["Watermelon Sugar", "Harry Styles"],
  ["Sign of the Times", "Harry Styles"],
  ["Adore You", "Harry Styles"],
  ["Late Night Talking", "Harry Styles"],
  ["Golden", "Harry Styles"],
  ["As It Was", "Harry Styles"],
  ["Flowers", "Miley Cyrus"],
  ["Wrecking Ball", "Miley Cyrus"],
  ["Party in the U.S.A.", "Miley Cyrus"],
  ["The Climb", "Miley Cyrus"],
  ["We Can't Stop", "Miley Cyrus"],
  ["drivers license", "Olivia Rodrigo"],
  ["good 4 u", "Olivia Rodrigo"],
  ["deja vu", "Olivia Rodrigo"],
  ["brutal", "Olivia Rodrigo"],
  ["Ghost", "Justin Bieber"],
  ["Intentions", "Justin Bieber"],
  ["Let Me Love You", "DJ Snake"],
  ["Turn Down for What", "DJ Snake"],
  ["Taki Taki", "DJ Snake"],
  ["Despacito", "Luis Fonsi"],
  ["Mi Gente", "J Balvin"],
  ["I Like It", "Cardi B"],
  ["Havana", "Camila Cabello"],
  ["Señorita", "Camila Cabello"],
  ["Don't Go Yet", "Camila Cabello"],
  ["Never Be the Same", "Camila Cabello"],
  ["Thank U, Next", "Ariana Grande"],
  ["7 rings", "Ariana Grande"],
  ["positions", "Ariana Grande"],
  ["into you", "Ariana Grande"],
  ["Side To Side", "Ariana Grande"],
  ["Problem", "Ariana Grande"],
  ["Break Free", "Ariana Grande"],
  ["No Tears Left to Cry", "Ariana Grande"],
  ["we can't be friends", "Ariana Grande"],
  ["yes, and?", "Ariana Grande"],
  ["good 4 u", "Olivia Rodrigo"],
  ["About Damn Time", "Lizzo"],
  ["Truth Hurts", "Lizzo"],
  ["Juice", "Lizzo"],
  ["Good as Hell", "Lizzo"],
  ["Butter", "BTS"],
  ["Dynamite", "BTS"],
  ["Permission to Dance", "BTS"],
  ["Boy With Luv", "BTS"],
  ["Pink Venom", "BLACKPINK"],
  ["How You Like That", "BLACKPINK"],
  ["DDU-DU DDU-DU", "BLACKPINK"],
  ["Kill This Love", "BLACKPINK"],
  ["APT.", "ROSÉ"],
  ["On The Ground", "ROSÉ"],
  ["LALISA", "LISA"],
  ["Money", "LISA"],
  ["Cupid", "FIFTY FIFTY"],
  ["Hype Boy", "NewJeans"],
  ["OMG", "NewJeans"],
  ["Super Shy", "NewJeans"],
  ["Ditto", "NewJeans"],
  ["Euphoria", "Kendrick Lamar"],
  ["All The Stars", "Kendrick Lamar"],
  ["LOYALTY.", "Kendrick Lamar"],
  ["See You Again", "Tyler, The Creator"],
  ["EARFQUAKE", "Tyler, The Creator"],
  ["NEW MAGIC WAND", "Tyler, The Creator"],
  ["I THINK", "Tyler, The Creator"],
  ["Pink + White", "Frank Ocean"],
  ["Thinkin Bout You", "Frank Ocean"],
  ["Nights", "Frank Ocean"],
  ["Ivy", "Frank Ocean"],
  ["Chanel", "Frank Ocean"],
  ["Redbone", "Childish Gambino"],
  ["This Is America", "Childish Gambino"],
  ["3005", "Childish Gambino"],
  ["Sweater Weather", "The Neighbourhood"],
  ["Daddy Issues", "The Neighbourhood"],
  ["The Less I Know The Better", "Tame Impala"],
  ["Let It Happen", "Tame Impala"],
  ["Borderline", "Tame Impala"],
  ["Elephant", "Tame Impala"],
  ["Instant Crush", "Daft Punk"],
  ["Harder, Better, Faster, Stronger", "Daft Punk"],
  ["Something About Us", "Daft Punk"],
  ["Midnight City", "M83"],
  ["The Middle", "Jimmy Eat World"],
  ["All The Small Things", "blink-182"],
  ["I Miss You", "blink-182"],
  ["What's My Age Again?", "blink-182"],
  ["In the End", "Linkin Park"],
  ["Numb", "Linkin Park"],
  ["Crawling", "Linkin Park"],
  ["What I've Done", "Linkin Park"],
  ["Faint", "Linkin Park"],
  ["Chop Suey!", "System Of A Down"],
  ["Toxicity", "System Of A Down"],
  ["Aerials", "System Of A Down"],
  ["Killing in the Name", "Rage Against The Machine"],
  ["Bulls on Parade", "Rage Against The Machine"],
  ["Everlong", "Foo Fighters"],
  ["The Pretender", "Foo Fighters"],
  ["Best of You", "Foo Fighters"],
  ["Learn to Fly", "Foo Fighters"],
  ["Californication", "Red Hot Chili Peppers"],
  ["Under the Bridge", "Red Hot Chili Peppers"],
  ["Can't Stop", "Red Hot Chili Peppers"],
  ["Dani California", "Red Hot Chili Peppers"],
  ["Scar Tissue", "Red Hot Chili Peppers"],
  ["Otherside", "Red Hot Chili Peppers"],
  ["Creep", "Radiohead"],
  ["Karma Police", "Radiohead"],
  ["No Surprises", "Radiohead"],
  ["High and Dry", "Radiohead"],
  ["Yellow", "Coldplay"],
  ["Wonderwall", "Oasis"],
  ["Don't Look Back in Anger", "Oasis"],
  ["Champagne Supernova", "Oasis"],
  ["Live Forever", "Oasis"],
  ["Song 2", "Blur"],
  ["Bittersweet Symphony", "The Verve"],
  ["Bitter Sweet Symphony", "The Verve"],
  ["Common People", "Pulp"],
  ["Zombie", "The Cranberries"],
  ["Linger", "The Cranberries"],
  ["Dreams", "The Cranberries"],
  ["Iris", "Goo Goo Dolls"],
  ["Slide", "Goo Goo Dolls"],
  ["I Want It That Way", "Backstreet Boys"],
  ["Everybody (Backstreet's Back)", "Backstreet Boys"],
  ["Bye Bye Bye", "NSYNC"],
  ["It's Gonna Be Me", "NSYNC"],
  ["...Baby One More Time", "Britney Spears"],
  ["Toxic", "Britney Spears"],
  ["Oops!...I Did It Again", "Britney Spears"],
  ["Gimme More", "Britney Spears"],
  ["Circus", "Britney Spears"],
  ["Genie in a Bottle", "Christina Aguilera"],
  ["Beautiful", "Christina Aguilera"],
  ["Lady Marmalade", "Christina Aguilera"],
  ["Since U Been Gone", "Kelly Clarkson"],
  ["Stronger (What Doesn't Kill You)", "Kelly Clarkson"],
  ["Because of You", "Kelly Clarkson"],
  ["Mr. Brightside", "The Killers"],
  ["Somebody Told Me", "The Killers"],
  ["Human", "The Killers"],
  ["When You Were Young", "The Killers"],
  ["Take Me Out", "Franz Ferdinand"],
  ["Do I Wanna Know?", "Arctic Monkeys"],
  ["I Bet You Look Good on the Dancefloor", "Arctic Monkeys"],
  ["R U Mine?", "Arctic Monkeys"],
  ["505", "Arctic Monkeys"],
  ["Fluorescent Adolescent", "Arctic Monkeys"],
  ["Why'd You Only Call Me When You're High?", "Arctic Monkeys"],
  ["Last Nite", "The Strokes"],
  ["Reptilia", "The Strokes"],
  ["Someday", "The Strokes"],
  ["You Only Live Once", "The Strokes"],
  ["Seven Nation Army", "The White Stripes"],
  ["Fell in Love With a Girl", "The White Stripes"],
  ["Icky Thump", "The White Stripes"],
  ["Lonely Boy", "The Black Keys"],
  ["Tighten Up", "The Black Keys"],
  ["Howlin' for You", "The Black Keys"],
  ["Gold on the Ceiling", "The Black Keys"],
  ["Use Somebody", "Kings of Leon"],
  ["Sex on Fire", "Kings of Leon"],
  ["Pumped Up Kicks", "Foster the People"],
  ["Sit Next to Me", "Foster the People"],
  ["Electric Feel", "MGMT"],
  ["Kids", "MGMT"],
  ["Little Dark Age", "MGMT"],
  ["Feel Good Inc.", "Gorillaz"],
  ["Clint Eastwood", "Gorillaz"],
  ["Feel It Still", "Portugal. The Man"],
  ["Africa", "Toto"],
  ["Hold the Line", "Toto"],
  ["Don't Stop Me Now", "Queen"],
  ["Another One Bites the Dust", "Queen"],
  ["We Will Rock You", "Queen"],
  ["We Are the Champions", "Queen"],
  ["Somebody to Love", "Queen"],
  ["Under Pressure", "Queen"],
  ["Crazy Little Thing Called Love", "Queen"],
  ["Don't Stop Believin'", "Journey"],
  ["Any Way You Want It", "Journey"],
  ["Separate Ways (Worlds Apart)", "Journey"],
  ["Livin' on a Prayer", "Bon Jovi"],
  ["You Give Love a Bad Name", "Bon Jovi"],
  ["It's My Life", "Bon Jovi"],
  ["Sweet Child O' Mine", "Guns N' Roses"],
  ["Welcome to the Jungle", "Guns N' Roses"],
  ["November Rain", "Guns N' Roses"],
  ["Paradise City", "Guns N' Roses"],
  ["Enter Sandman", "Metallica"],
  ["Nothing Else Matters", "Metallica"],
  ["Master of Puppets", "Metallica"],
  ["One", "Metallica"],
  ["Back In Black", "AC/DC"],
  ["Highway to Hell", "AC/DC"],
  ["Thunderstruck", "AC/DC"],
  ["You Shook Me All Night Long", "AC/DC"],
  ["TNT", "AC/DC"],
  ["Smells Like Teen Spirit", "Nirvana"],
  ["Come as You Are", "Nirvana"],
  ["Lithium", "Nirvana"],
  ["Heart-Shaped Box", "Nirvana"],
  ["In Bloom", "Nirvana"],
  ["Black Hole Sun", "Soundgarden"],
  ["Even Flow", "Pearl Jam"],
  ["Alive", "Pearl Jam"],
  ["Jeremy", "Pearl Jam"],
  ["Better Man", "Pearl Jam"],
  ["Under the Bridge", "Red Hot Chili Peppers"],
  ["Losing My Religion", "R.E.M."],
  ["Everybody Hurts", "R.E.M."],
  ["Shiny Happy People", "R.E.M."],
  ["With or Without You", "U2"],
  ["Beautiful Day", "U2"],
  ["One", "U2"],
  ["Sunday Bloody Sunday", "U2"],
  ["Where the Streets Have No Name", "U2"],
  ["Take On Me", "a-ha"],
  ["The Final Countdown", "Europe"],
  ["Eye of the Tiger", "Survivor"],
  ["Jump", "Van Halen"],
  ["Panama", "Van Halen"],
  ["Africa", "Toto"],
  ["Every Breath You Take", "The Police"],
  ["Roxanne", "The Police"],
  ["Message in a Bottle", "The Police"],
  ["Don't You (Forget About Me)", "Simple Minds"],
  ["Everybody Wants to Rule the World", "Tears for Fears"],
  ["Shout", "Tears for Fears"],
  ["Sweet Dreams (Are Made of This)", "Eurythmics"],
  ["Here Comes the Rain Again", "Eurythmics"],
  ["Girls Just Want to Have Fun", "Cyndi Lauper"],
  ["Time After Time", "Cyndi Lauper"],
  ["Like a Prayer", "Madonna"],
  ["Like a Virgin", "Madonna"],
  ["Vogue", "Madonna"],
  ["Hung Up", "Madonna"],
  ["Material Girl", "Madonna"],
  ["Billie Jean", "Michael Jackson"],
  ["Beat It", "Michael Jackson"],
  ["Thriller", "Michael Jackson"],
  ["Smooth Criminal", "Michael Jackson"],
  ["Bad", "Michael Jackson"],
  ["Don't Stop 'Til You Get Enough", "Michael Jackson"],
  ["The Way You Make Me Feel", "Michael Jackson"],
  ["Black or White", "Michael Jackson"],
  ["Rock With You", "Michael Jackson"],
  ["I Want You Back", "The Jackson 5"],
  ["ABC", "The Jackson 5"],
  ["I Wanna Dance with Somebody", "Whitney Houston"],
  ["I Will Always Love You", "Whitney Houston"],
  ["Greatest Love of All", "Whitney Houston"],
  ["How Will I Know", "Whitney Houston"],
  ["Respect", "Aretha Franklin"],
  ["Think", "Aretha Franklin"],
  ["What's Going On", "Marvin Gaye"],
  ["Let's Get It On", "Marvin Gaye"],
  ["Sexual Healing", "Marvin Gaye"],
  ["Superstition", "Stevie Wonder"],
  ["Sir Duke", "Stevie Wonder"],
  ["I Wish", "Stevie Wonder"],
  ["Isn't She Lovely", "Stevie Wonder"],
  ["Signed, Sealed, Delivered (I'm Yours)", "Stevie Wonder"],
  ["Let's Stay Together", "Al Green"],
  ["Lovely Day", "Bill Withers"],
  ["Ain't No Sunshine", "Bill Withers"],
  ["Lean on Me", "Bill Withers"],
  ["September", "Earth, Wind & Fire"],
  ["Boogie Wonderland", "Earth, Wind & Fire"],
  ["Let's Groove", "Earth, Wind & Fire"],
  ["Stayin' Alive", "Bee Gees"],
  ["Night Fever", "Bee Gees"],
  ["How Deep Is Your Love", "Bee Gees"],
  ["Dancing Queen", "ABBA"],
  ["Mamma Mia", "ABBA"],
  ["Gimme! Gimme! Gimme! (A Man After Midnight)", "ABBA"],
  ["Waterloo", "ABBA"],
  ["Take a Chance on Me", "ABBA"],
  ["I Will Survive", "Gloria Gaynor"],
  ["Y.M.C.A.", "Village People"],
  ["Le Freak", "Chic"],
  ["Good Times", "Chic"],
  ["Celebration", "Kool & The Gang"],
  ["Get Down On It", "Kool & The Gang"],
  ["Don't Stop 'Til You Get Enough", "Michael Jackson"],
  ["Rock Your Baby", "George McCrae"],
  ["Hotel California", "Eagles"],
  ["Take It Easy", "Eagles"],
  ["Desperado", "Eagles"],
  ["Life in the Fast Lane", "Eagles"],
  ["Go Your Own Way", "Fleetwood Mac"],
  ["Dreams", "Fleetwood Mac"],
  ["The Chain", "Fleetwood Mac"],
  ["Everywhere", "Fleetwood Mac"],
  ["Landslide", "Fleetwood Mac"],
  ["Rhiannon", "Fleetwood Mac"],
  ["Imagine", "John Lennon"],
  ["Hey Jude", "The Beatles"],
  ["Let It Be", "The Beatles"],
  ["Come Together", "The Beatles"],
  ["Here Comes the Sun", "The Beatles"],
  ["Yesterday", "The Beatles"],
  ["Help!", "The Beatles"],
  ["Twist and Shout", "The Beatles"],
  ["A Hard Day's Night", "The Beatles"],
  ["Something", "The Beatles"],
  ["While My Guitar Gently Weeps", "The Beatles"],
  ["Stairway to Heaven", "Led Zeppelin"],
  ["Immigrant Song", "Led Zeppelin"],
  ["Black Dog", "Led Zeppelin"],
  ["Whole Lotta Love", "Led Zeppelin"],
  ["Kashmir", "Led Zeppelin"],
  ["Comfortably Numb", "Pink Floyd"],
  ["Wish You Were Here", "Pink Floyd"],
  ["Another Brick in the Wall, Pt. 2", "Pink Floyd"],
  ["Money", "Pink Floyd"],
  ["Time", "Pink Floyd"],
  ["Paint It, Black", "The Rolling Stones"],
  ["Satisfaction", "The Rolling Stones"],
  ["Gimme Shelter", "The Rolling Stones"],
  ["Start Me Up", "The Rolling Stones"],
  ["Angie", "The Rolling Stones"],
  ["Sympathy for the Devil", "The Rolling Stones"],
  ["Like a Rolling Stone", "Bob Dylan"],
  ["Knockin' on Heaven's Door", "Bob Dylan"],
  ["The Times They Are A-Changin'", "Bob Dylan"],
  ["Blowin' in the Wind", "Bob Dylan"],
  ["No Woman, No Cry", "Bob Marley & The Wailers"],
  ["Three Little Birds", "Bob Marley & The Wailers"],
  ["Could You Be Loved", "Bob Marley & The Wailers"],
  ["One Love", "Bob Marley & The Wailers"],
  ["Redemption Song", "Bob Marley & The Wailers"],
  ["Is This Love", "Bob Marley & The Wailers"],
  ["Jamming", "Bob Marley & The Wailers"],
  ["Purple Rain", "Prince"],
  ["When Doves Cry", "Prince"],
  ["Kiss", "Prince"],
  ["Little Red Corvette", "Prince"],
  ["1999", "Prince"],
  ["Let's Go Crazy", "Prince"],
  ["Crazy in Love", "Beyoncé"],
  ["Single Ladies (Put a Ring on It)", "Beyoncé"],
  ["Irreplaceable", "Beyoncé"],
  ["Halo", "Beyoncé"],
  ["Formation", "Beyoncé"],
  ["Crazy", "Gnarls Barkley"],
  ["Forget You", "CeeLo Green"],
  ["Rehab", "Amy Winehouse"],
  ["Back to Black", "Amy Winehouse"],
  ["Valerie", "Amy Winehouse"],
  ["Rolling in the Deep", "Adele"],
  ["Set Fire to the Rain", "Adele"],
  ["Rumour Has It", "Adele"],
  ["Skyfall", "Adele"],
  ["Chasing Pavements", "Adele"],
  ["When I Was Your Man", "Bruno Mars"],
  ["The Lazy Song", "Bruno Mars"],
  ["Locked Out of Heaven", "Bruno Mars"],
  ["That's What I Like", "Bruno Mars"],
  ["Leave The Door Open", "Bruno Mars"],
  ["Die With A Smile", "Lady Gaga"],
  ["Shallow", "Lady Gaga"],
  ["Always Remember Us This Way", "Lady Gaga"],
  ["Bad Romance", "Lady Gaga"],
  ["Poker Face", "Lady Gaga"],
  ["Just Dance", "Lady Gaga"],
  ["Born This Way", "Lady Gaga"],
  ["All of Me", "John Legend"],
  ["Ordinary People", "John Legend"],
  ["Glory", "John Legend"],
  ["Thinking Out Loud", "Ed Sheeran"],
  ["Photograph", "Ed Sheeran"],
  ["Castle on the Hill", "Ed Sheeran"],
  ["Perfect", "Ed Sheeran"],
  ["Shape of You", "Ed Sheeran"],
  ["Bad Habits", "Ed Sheeran"],
  ["Shivers", "Ed Sheeran"],
  ["The A Team", "Ed Sheeran"],
  ["Happier", "Ed Sheeran"],
  ["Stay With Me", "Sam Smith"],
  ["I'm Not The Only One", "Sam Smith"],
  ["Too Good at Goodbyes", "Sam Smith"],
  ["Unholy", "Sam Smith"],
  ["Dancing With A Stranger", "Sam Smith"],
  ["Let It Go", "Idina Menzel"],
  ["A Thousand Years", "Christina Perri"],
  ["Jar of Hearts", "Christina Perri"],
  ["All of Me", "John Legend"],
  ["A Thousand Years", "Christina Perri"],
  ["See You Again", "Wiz Khalifa"],
  ["Black and Yellow", "Wiz Khalifa"],
  ["Young, Wild & Free", "Snoop Dogg"],
  ["Drop It Like It's Hot", "Snoop Dogg"],
  ["The Next Episode", "Dr. Dre"],
  ["Still D.R.E.", "Dr. Dre"],
  ["Forgot About Dre", "Dr. Dre"],
  ["In Da Club", "50 Cent"],
  ["Many Men", "50 Cent"],
  ["P.I.M.P.", "50 Cent"],
  ["Ms. Jackson", "OutKast"],
  ["Hey Ya!", "OutKast"],
  ["The Way You Move", "OutKast"],
  ["Roses", "OutKast"],
  ["Yeah!", "Usher"],
  ["Burn", "Usher"],
  ["OMG", "Usher"],
  ["DJ Got Us Fallin' in Love", "Usher"],
  ["Yeah!", "Usher"],
  ["Ignition (Remix)", "R. Kelly"],
  ["Promiscuous", "Nelly Furtado"],
  ["Maneater", "Nelly Furtado"],
  ["I'm Like a Bird", "Nelly Furtado"],
  ["Hips Don't Lie", "Shakira"],
  ["Whenever, Wherever", "Shakira"],
  ["Waka Waka (This Time for Africa)", "Shakira"],
  ["She Wolf", "Shakira"],
  ["La Tortura", "Shakira"],
  ["Gasolina", "Daddy Yankee"],
  ["Con Calma", "Daddy Yankee"],
  ["Dákiti", "Bad Bunny"],
  ["Tití Me Preguntó", "Bad Bunny"],
  ["Moscow Mule", "Bad Bunny"],
  ["Me Porto Bonito", "Bad Bunny"],
  ["Titi Me Pregunto", "Bad Bunny"],
  ["Despacito", "Luis Fonsi"],
  ["Échame La Culpa", "Luis Fonsi"],
  ["Mi Gente", "J Balvin"],
  ["Ginza", "J Balvin"],
  ["I Like It", "Cardi B"],
  ["Bodak Yellow", "Cardi B"],
  ["WAP", "Cardi B"],
  ["Havana", "Camila Cabello"],
  ["Señorita", "Shawn Mendes"],
  ["Stitches", "Shawn Mendes"],
  ["Treat You Better", "Shawn Mendes"],
  ["Mercy", "Shawn Mendes"],
  ["In My Blood", "Shawn Mendes"],
  ["What Makes You Beautiful", "One Direction"],
  ["Night Changes", "One Direction"],
  ["Best Song Ever", "One Direction"],
  ["Steal My Girl", "One Direction"],
  ["Story of My Life", "One Direction"],
  ["You Need To Calm Down", "Taylor Swift"],
  ["ME!", "Taylor Swift"],
  ["Look What You Made Me Do", "Taylor Swift"],
  ["Wildest Dreams", "Taylor Swift"],
  ["Style", "Taylor Swift"],
  ["Blank Space", "Taylor Swift"],
  ["Shake It Off", "Taylor Swift"],
  ["Love Story", "Taylor Swift"],
  ["You Belong With Me", "Taylor Swift"],
  ["All Too Well", "Taylor Swift"],
  ["cardigan", "Taylor Swift"],
  ["august", "Taylor Swift"],
  ["willow", "Taylor Swift"],
  ["Anti-Hero", "Taylor Swift"],
  ["Cruel Summer", "Taylor Swift"],
  ["Fortnight", "Taylor Swift"],
  ["Lavender Haze", "Taylor Swift"],
  ["Karma", "Taylor Swift"],
  ["Bejeweled", "Taylor Swift"],
  ["Bad Blood", "Taylor Swift"],
  ["I Knew You Were Trouble", "Taylor Swift"],
  ["We Are Never Ever Getting Back Together", "Taylor Swift"],
  ["22", "Taylor Swift"],
  ["Enchanted", "Taylor Swift"],
  ["Lover", "Taylor Swift"],
  ["The Man", "Taylor Swift"],
  ["Delicate", "Taylor Swift"],
  ["Don't Blame Me", "Taylor Swift"],
  ["Getaway Car", "Taylor Swift"],
  ["My Tears Ricochet", "Taylor Swift"],
  ["exile", "Taylor Swift"],
  ["betty", "Taylor Swift"],
  ["champagne problems", "Taylor Swift"],
  ["tolerate it", "Taylor Swift"],
  ["no body, no crime", "Taylor Swift"],
  ["the 1", "Taylor Swift"],
  ["This Love", "Maroon 5"],
  ["She Will Be Loved", "Maroon 5"],
  ["Makes Me Wonder", "Maroon 5"],
  ["Moves Like Jagger", "Maroon 5"],
  ["Payphone", "Maroon 5"],
  ["Maps", "Maroon 5"],
  ["Sugar", "Maroon 5"],
  ["Animals", "Maroon 5"],
  ["Girls Like You", "Maroon 5"],
  ["Memories", "Maroon 5"],
  ["Won't Go Home Without You", "Maroon 5"],
  ["Sunday Morning", "Maroon 5"],
  ["Harder to Breathe", "Maroon 5"],
  ["Misery", "Maroon 5"],
  ["One More Night", "Maroon 5"],
  ["Wake Me Up When September Ends", "Green Day"],
  ["Boulevard of Broken Dreams", "Green Day"],
  ["American Idiot", "Green Day"],
  ["Holiday", "Green Day"],
  ["Good Riddance (Time of Your Life)", "Green Day"],
  ["Basket Case", "Green Day"],
  ["When I Come Around", "Green Day"],
  ["Brain Stew", "Green Day"],
  ["Welcome to Paradise", "Green Day"],
  ["Still Into You", "Paramore"],
  ["Misery Business", "Paramore"],
  ["Ain't It Fun", "Paramore"],
  ["The Only Exception", "Paramore"],
  ["That's What You Get", "Paramore"],
  ["Decode", "Paramore"],
  ["Ignorance", "Paramore"],
  ["Hard Times", "Paramore"],
  ["Bring Me to Life", "Evanescence"],
  ["My Immortal", "Evanescence"],
  ["Going Under", "Evanescence"],
  ["Numb", "Linkin Park"],
  ["In the End", "Linkin Park"],
  ["What I've Done", "Linkin Park"],
  ["New Divide", "Linkin Park"],
  ["Bleed It Out", "Linkin Park"],
  ["Shadow of the Day", "Linkin Park"],
  ["Breaking the Habit", "Linkin Park"],
  ["Crawling", "Linkin Park"],
  ["Faint", "Linkin Park"],
  ["Somewhere I Belong", "Linkin Park"],
  ["Papercut", "Linkin Park"],
  ["One Step Closer", "Linkin Park"],
  ["Given Up", "Linkin Park"],
  ["Leave Out All The Rest", "Linkin Park"],
  ["Waiting for the End", "Linkin Park"],
  ["Burn It Down", "Linkin Park"],
  ["Heavy", "Linkin Park"],
  ["Lost", "Linkin Park"],
  ["The Emptiness Machine", "Linkin Park"],
  ["I Write Sins Not Tragedies", "Panic! At The Disco"],
  ["High Hopes", "Panic! At The Disco"],
  ["Victorious", "Panic! At The Disco"],
  ["Death of a Bachelor", "Panic! At The Disco"],
  ["This Is Gospel", "Panic! At The Disco"],
  ["Nine in the Afternoon", "Panic! At The Disco"],
  ["The Only Difference", "Panic! At The Disco"],
  ["Sugar, We're Goin Down", "Fall Out Boy"],
  ["Dance, Dance", "Fall Out Boy"],
  ["Thnks fr th Mmrs", "Fall Out Boy"],
  ["Centuries", "Fall Out Boy"],
  ["My Songs Know What You Did in the Dark", "Fall Out Boy"],
  ["Uma Thurman", "Fall Out Boy"],
  ["Immortals", "Fall Out Boy"],
  ["This Ain't a Scene, It's an Arms Race", "Fall Out Boy"],
  ["Dear Maria, Count Me In", "All Time Low"],
  ["Weightless", "All Time Low"],
  ["Dirty Little Secret", "The All-American Rejects"],
  ["Gives You Hell", "The All-American Rejects"],
  ["Move Along", "The All-American Rejects"],
  ["I Don't Care", "Fall Out Boy"],
  ["Teenagers", "My Chemical Romance"],
  ["Welcome to the Black Parade", "My Chemical Romance"],
  ["Helena", "My Chemical Romance"],
  ["I'm Not Okay (I Promise)", "My Chemical Romance"],
  ["Famous Last Words", "My Chemical Romance"],
  ["Na Na Na", "My Chemical Romance"],
  ["The Ghost of You", "My Chemical Romance"],
  ["I Miss You", "blink-182"],
  ["All The Small Things", "blink-182"],
  ["What's My Age Again?", "blink-182"],
  ["First Date", "blink-182"],
  ["Adam's Song", "blink-182"],
  ["Dammit", "blink-182"],
  ["Feeling This", "blink-182"],
  ["The Rock Show", "blink-182"],
  ["Stay Together for the Kids", "blink-182"],
  ["Ocean Avenue", "Yellowcard"],
  ["Only One", "Yellowcard"],
  ["The Anthem", "Good Charlotte"],
  ["Lifestyles of the Rich & Famous", "Good Charlotte"],
  ["I Write Sins Not Tragedies", "Panic! At The Disco"],
  ["Mr. Brightside", "The Killers"],
  ["Somebody That I Used to Know", "Gotye"],
  ["Somebody To Love", "Queen"],
  ["Bohemian Rhapsody", "Queen"],
  ["Don't Stop Me Now", "Queen"],
  ["We Will Rock You", "Queen"],
  ["Another One Bites the Dust", "Queen"],
  ["Crazy Little Thing Called Love", "Queen"],
  ["Radio Ga Ga", "Queen"],
  ["I Want to Break Free", "Queen"],
  ["Killer Queen", "Queen"],
  ["Fat Bottomed Girls", "Queen"],
  ["Bicycle Race", "Queen"],
  ["You're My Best Friend", "Queen"],
  ["The Show Must Go On", "Queen"],
  ["Who Wants to Live Forever", "Queen"],
  ["Love of My Life", "Queen"],
  ["Good Old-Fashioned Lover Boy", "Queen"],
  ["Hammer to Fall", "Queen"],
  ["A Kind of Magic", "Queen"],
  ["One Vision", "Queen"],
  ["Princes of the Universe", "Queen"],
  ["Flash", "Queen"],
  ["It's a Kind of Magic", "Queen"],
  ["Spread Your Wings", "Queen"],
  ["Now I'm Here", "Queen"],
  ["Keep Yourself Alive", "Queen"],
  ["Tie Your Mother Down", "Queen"],
  ["Stone Cold Crazy", "Queen"],
  ["Dragon Attack", "Queen"],
  ["Play the Game", "Queen"],
  ["Save Me", "Queen"],
  ["Need Your Loving Tonight", "Queen"],
  ["I'm Going Slightly Mad", "Queen"],
  ["These Are the Days of Our Lives", "Queen"],
  ["I'm in Love with My Car", "Queen"],
  ["I'm a Believer", "The Monkees"],
  ["Daydream Believer", "The Monkees"],
  ["Last Train to Clarksville", "The Monkees"],
  ["I'm a Believer", "Smash Mouth"],
  ["All Star", "Smash Mouth"],
  ["Walkin' on the Sun", "Smash Mouth"],
  ["Then The Morning Comes", "Smash Mouth"],
  ["Hook", "Blues Traveler"],
  ["Run-Around", "Blues Traveler"],
  ["Semi-Charmed Life", "Third Eye Blind"],
  ["Jumper", "Third Eye Blind"],
  ["Never Let You Go", "Third Eye Blind"],
  ["How's It Going to Be", "Third Eye Blind"],
  ["Iris", "Goo Goo Dolls"],
  ["Slide", "Goo Goo Dolls"],
  ["Name", "Goo Goo Dolls"],
  ["Black Balloon", "Goo Goo Dolls"],
  ["All You Wanted", "Michelle Branch"],
  ["Everywhere", "Michelle Branch"],
  ["A Thousand Miles", "Vanessa Carlton"],
  ["White Flag", "Dido"],
  ["Thank You", "Dido"],
  ["Here With Me", "Dido"],
  ["Complicated", "Avril Lavigne"],
  ["Sk8er Boi", "Avril Lavigne"],
  ["I'm With You", "Avril Lavigne"],
  ["Girlfriend", "Avril Lavigne"],
  ["My Happy Ending", "Avril Lavigne"],
  ["Keep Holding On", "Avril Lavigne"],
  ["When You're Gone", "Avril Lavigne"],
  ["What the Hell", "Avril Lavigne"],
  ["Here's to Never Growing Up", "Avril Lavigne"],
  ["Hot", "Avril Lavigne"],
  ["Nobody's Home", "Avril Lavigne"],
  ["Don't Tell Me", "Avril Lavigne"],
  ["Losing Grip", "Avril Lavigne"],
  ["Breakaway", "Kelly Clarkson"],
  ["Since U Been Gone", "Kelly Clarkson"],
  ["Behind These Hazel Eyes", "Kelly Clarkson"],
  ["Because of You", "Kelly Clarkson"],
  ["Walk Away", "Kelly Clarkson"],
  ["Already Gone", "Kelly Clarkson"],
  ["My Life Would Suck Without You", "Kelly Clarkson"],
  ["Stronger (What Doesn't Kill You)", "Kelly Clarkson"],
  ["Miss Independent", "Kelly Clarkson"],
  ["A Moment Like This", "Kelly Clarkson"],
  ["Piece by Piece", "Kelly Clarkson"],
  ["Heartbreaker", "Pat Benatar"],
  ["Love Is a Battlefield", "Pat Benatar"],
  ["Hit Me With Your Best Shot", "Pat Benatar"],
  ["We Belong", "Pat Benatar"],
  ["Total Eclipse of the Heart", "Bonnie Tyler"],
  ["Holding Out for a Hero", "Bonnie Tyler"],
  ["It's a Heartache", "Bonnie Tyler"],
  ["I Love Rock 'n' Roll", "Joan Jett & the Blackhearts"],
  ["Bad Reputation", "Joan Jett & the Blackhearts"],
  ["Crimson and Clover", "Joan Jett & the Blackhearts"],
  ["Cherry Bomb", "The Runaways"],
  ["Barracuda", "Heart"],
  ["Alone", "Heart"],
  ["Magic Man", "Heart"],
  ["Crazy on You", "Heart"],
  ["These Dreams", "Heart"],
  ["What About Love", "Heart"],
  ["All I Wanna Do", "Sheryl Crow"],
  ["Soak Up the Sun", "Sheryl Crow"],
  ["If It Makes You Happy", "Sheryl Crow"],
  ["Everyday Is a Winding Road", "Sheryl Crow"],
  ["My Favorite Mistake", "Sheryl Crow"],
  ["Strong Enough", "Sheryl Crow"],
  ["Tomorrow Never Dies", "Sheryl Crow"],
  ["Picture", "Kid Rock"],
  ["All Summer Long", "Kid Rock"],
  ["Bawitdaba", "Kid Rock"],
  ["Cowboy", "Kid Rock"],
  ["Only God Knows Why", "Kid Rock"],
  ["Born to Be Wild", "Steppenwolf"],
  ["Magic Carpet Ride", "Steppenwolf"],
  ["Sweet Home Alabama", "Lynyrd Skynyrd"],
  ["Free Bird", "Lynyrd Skynyrd"],
  ["Simple Man", "Lynyrd Skynyrd"],
  ["Gimme Three Steps", "Lynyrd Skynyrd"],
  ["Tuesday's Gone", "Lynyrd Skynyrd"],
  ["Call Me the Breeze", "Lynyrd Skynyrd"],
  ["That Smell", "Lynyrd Skynyrd"],
  ["What's Your Name", "Lynyrd Skynyrd"],
  ["Saturday Night Special", "Lynyrd Skynyrd"],
  ["The Joker", "Steve Miller Band"],
  ["Fly Like an Eagle", "Steve Miller Band"],
  ["Abracadabra", "Steve Miller Band"],
  ["Take the Money and Run", "Steve Miller Band"],
  ["Rock'n Me", "Steve Miller Band"],
  ["Jet Airliner", "Steve Miller Band"],
  ["Jungle Love", "Steve Miller Band"],
  ["Swingtown", "Steve Miller Band"],
  ["More Than a Feeling", "Boston"],
  ["Peace of Mind", "Boston"],
  ["Foreplay / Long Time", "Boston"],
  ["Don't Look Back", "Boston"],
  ["Amanda", "Boston"],
  ["Hitch a Ride", "Boston"],
  ["Rock and Roll Band", "Boston"],
  ["Smokin'", "Boston"],
  ["Let Me Take You Home Tonight", "Boston"],
  ["Cool the Engines", "Boston"],
  ["Carry On Wayward Son", "Kansas"],
  ["Dust in the Wind", "Kansas"],
  ["Point of Know Return", "Kansas"],
  ["Play the Game Tonight", "Kansas"],
  ["Hold On", "Kansas"],
  ["The Wall", "Kansas"],
  ["People of the South Wind", "Kansas"],
  ["Journey from Mariabronn", "Kansas"],
  ["Be Good to Yourself", "Journey"],
  ["Faithfully", "Journey"],
  ["Open Arms", "Journey"],
  ["Wheel in the Sky", "Journey"],
  ["Lights", "Journey"],
  ["Lovin', Touchin', Squeezin'", "Journey"],
  ["Who's Crying Now", "Journey"],
  ["Separate Ways (Worlds Apart)", "Journey"],
  ["Don't Stop Believin'", "Journey"],
  ["Any Way You Want It", "Journey"],
  ["Stone in Love", "Journey"],
  ["Ask the Lonely", "Journey"],
  ["Only the Young", "Journey"],
  ["Girl Can't Help It", "Journey"],
  ["I'll Be Alright Without You", "Journey"],
  ["When You Love a Woman", "Journey"],
  ["Lovely Day", "Bill Withers"],
  ["Just the Two of Us", "Bill Withers"],
  ["Let's Stay Together", "Al Green"],
  ["Tired of Being Alone", "Al Green"],
  ["I Can't Help Myself (Sugar Pie Honey Bunch)", "Four Tops"],
  ["My Girl", "The Temptations"],
  ["Ain't Too Proud to Beg", "The Temptations"],
  ["I Heard It Through the Grapevine", "Marvin Gaye"],
  ["I Want You Back", "The Jackson 5"],
  ["ABC", "The Jackson 5"],
  ["Dancing in the Street", "Martha Reeves & The Vandellas"],
  ["Stop! In the Name of Love", "The Supremes"],
  ["You Can't Hurry Love", "The Supremes"],
  ["My Cherie Amour", "Stevie Wonder"],
  ["You Are the Sunshine of My Life", "Stevie Wonder"],
  ["Higher Ground", "Stevie Wonder"],
  ["Living for the City", "Stevie Wonder"],
  ["I Feel Good", "James Brown"],
  ["Papa's Got a Brand New Bag", "James Brown"],
  ["Get Up (I Feel Like Being a) Sex Machine", "James Brown"],
  ["What's Going On", "Marvin Gaye"],
  ["Mercy Mercy Me (The Ecology)", "Marvin Gaye"],
  ["Ain't No Mountain High Enough", "Marvin Gaye"],
  ["You're All I Need to Get By", "Marvin Gaye"],
  ["Let's Get It On", "Marvin Gaye"],
  ["Got to Give It Up", "Marvin Gaye"],
  ["I Want You", "Marvin Gaye"],
  ["Sexual Healing", "Marvin Gaye"],
  ["Family Affair", "Sly & The Family Stone"],
  ["Everyday People", "Sly & The Family Stone"],
  ["Thank You (Falettinme Be Mice Elf Agin)", "Sly & The Family Stone"],
  ["Lean on Me", "Bill Withers"],
  ["Use Me", "Bill Withers"],
  ["Grandma's Hands", "Bill Withers"],
  ["Kiss From a Rose", "Seal"],
  ["Crazy", "Seal"],
  ["Fly Away", "Lenny Kravitz"],
  ["Are You Gonna Go My Way", "Lenny Kravitz"],
  ["American Woman", "Lenny Kravitz"],
  ["It Ain't Over 'til It's Over", "Lenny Kravitz"],
  ["Smooth", "Santana"],
  ["Maria Maria", "Santana"],
  ["Black Magic Woman", "Santana"],
  ["Oye Como Va", "Santana"],
  ["Evil Ways", "Santana"],
  ["Smooth Operator", "Sade"],
  ["No Ordinary Love", "Sade"],
  ["By Your Side", "Sade"],
  ["The Sweetest Taboo", "Sade"],
  ["Your Song", "Elton John"],
  ["Tiny Dancer", "Elton John"],
  ["Rocket Man", "Elton John"],
  ["Bennie and the Jets", "Elton John"],
  ["I'm Still Standing", "Elton John"],
  ["Crocodile Rock", "Elton John"],
  ["Don't Go Breaking My Heart", "Elton John"],
  ["Candle in the Wind", "Elton John"],
  ["Goodbye Yellow Brick Road", "Elton John"],
  ["Saturday Night's Alright for Fighting", "Elton John"],
  ["Daniel", "Elton John"],
  ["Don't Let the Sun Go Down on Me", "Elton John"],
  ["Circle of Life", "Elton John"],
  ["Can You Feel the Love Tonight", "Elton John"],
  ["Piano Man", "Billy Joel"],
  ["Uptown Girl", "Billy Joel"],
  ["We Didn't Start the Fire", "Billy Joel"],
  ["Just the Way You Are", "Billy Joel"],
  ["It's Still Rock and Roll to Me", "Billy Joel"],
  ["Movin' Out (Anthony's Song)", "Billy Joel"],
  ["New York State of Mind", "Billy Joel"],
  ["The River of Dreams", "Billy Joel"],
  ["Vienna", "Billy Joel"],
  ["Only the Good Die Young", "Billy Joel"],
  ["My Heart Will Go On", "Celine Dion"],
  ["The Power of Love", "Celine Dion"],
  ["It's All Coming Back to Me Now", "Celine Dion"],
  ["Because You Loved Me", "Celine Dion"],
  ["That's the Way It Is", "Celine Dion"],
  ["I Want It That Way", "Backstreet Boys"],
  ["Everybody (Backstreet's Back)", "Backstreet Boys"],
  ["As Long as You Love Me", "Backstreet Boys"],
  ["Larger Than Life", "Backstreet Boys"],
  ["Quit Playing Games (With My Heart)", "Backstreet Boys"],
  ["Bye Bye Bye", "*NSYNC"],
  ["It's Gonna Be Me", "*NSYNC"],
  ["Tearin' Up My Heart", "*NSYNC"],
  ["Girlfriend", "*NSYNC"],
  ["Pop", "*NSYNC"],
  ["...Baby One More Time", "Britney Spears"],
  ["Oops!...I Did It Again", "Britney Spears"],
  ["Toxic", "Britney Spears"],
  ["I'm a Slave 4 U", "Britney Spears"],
  ["Gimme More", "Britney Spears"],
  ["Circus", "Britney Spears"],
  ["Womanizer", "Britney Spears"],
  ["Piece of Me", "Britney Spears"],
  ["Sometimes", "Britney Spears"],
  ["Lucky", "Britney Spears"],
  ["Stronger", "Britney Spears"],
  ["Overprotected", "Britney Spears"],
  ["I'm Not a Girl, Not Yet a Woman", "Britney Spears"],
  ["Everytime", "Britney Spears"],
  ["If U Seek Amy", "Britney Spears"],
  ["Hold It Against Me", "Britney Spears"],
  ["Till the World Ends", "Britney Spears"],
  ["I Wanna Go", "Britney Spears"],
  ["Work Bitch", "Britney Spears"],
  ["Pretty Girls", "Britney Spears"],
  ["Slumber Party", "Britney Spears"],
  ["Make Me...", "Britney Spears"],
  ["Genie in a Bottle", "Christina Aguilera"],
  ["What a Girl Wants", "Christina Aguilera"],
  ["Come On Over Baby (All I Want Is You)", "Christina Aguilera"],
  ["Dirrty", "Christina Aguilera"],
  ["Fighter", "Christina Aguilera"],
  ["Beautiful", "Christina Aguilera"],
  ["Ain't No Other Man", "Christina Aguilera"],
  ["Candyman", "Christina Aguilera"],
  ["Lady Marmalade", "Christina Aguilera"],
  ["Say My Name", "Destiny's Child"],
  ["Survivor", "Destiny's Child"],
  ["Independent Women, Pt. I", "Destiny's Child"],
  ["Bootylicious", "Destiny's Child"],
  ["Jumpin', Jumpin'", "Destiny's Child"],
  ["Bills, Bills, Bills", "Destiny's Child"],
  ["Emotion", "Destiny's Child"],
  ["Lose My Breath", "Destiny's Child"],
  ["Soldier", "Destiny's Child"],
  ["Cater 2 U", "Destiny's Child"],
  ["No, No, No", "Destiny's Child"],
  ["Bug a Boo", "Destiny's Child"],
  ["With You", "Chris Brown"],
  ["Forever", "Chris Brown"],
  ["Run It!", "Chris Brown"],
  ["Yeah 3x", "Chris Brown"],
  ["Don't Wake Me Up", "Chris Brown"],
  ["Loyal", "Chris Brown"],
  ["Look at Me Now", "Chris Brown"],
  ["Turn Up the Music", "Chris Brown"],
  ["Fine China", "Chris Brown"],
  ["New Flame", "Chris Brown"],
  ["Go Crazy", "Chris Brown"],
  ["Under the Influence", "Chris Brown"],
  ["No Guidance", "Chris Brown"],
  ["Beautiful People", "Chris Brown"],
  ["Kiss Kiss", "Chris Brown"],
  ["Yo (Excuse Me Miss)", "Chris Brown"],
  ["Gimme That", "Chris Brown"],
  ["Wall to Wall", "Chris Brown"],
  ["Take You Down", "Chris Brown"],
  ["I Can Transform Ya", "Chris Brown"],
  ["Deuces", "Chris Brown"],
  ["She Ain't You", "Chris Brown"],
  ["Next To You", "Chris Brown"],
  ["Don't Judge Me", "Chris Brown"],
  ["Fine By Me", "Chris Brown"],
  ["Don't Think They Know", "Chris Brown"],
  ["Love More", "Chris Brown"],
  ["New Flame", "Chris Brown"],
  ["Ayo", "Chris Brown"],
  ["Liquor", "Chris Brown"],
  ["Zero", "Chris Brown"],
  ["Back To Sleep", "Chris Brown"],
  ["Grass Ain't Greener", "Chris Brown"],
  ["Privacy", "Chris Brown"],
  ["Pills & Automobiles", "Chris Brown"],
  ["Questions", "Chris Brown"],
  ["Tempo", "Chris Brown"],
  ["Undecided", "Chris Brown"],
  ["Heat", "Chris Brown"],
  ["No Guidance", "Chris Brown"],
  ["Come Together", "The Beatles"],
  ["Let It Be", "The Beatles"],
  ["Hey Jude", "The Beatles"],
  ["Yesterday", "The Beatles"],
  ["Help!", "The Beatles"],
  ["A Hard Day's Night", "The Beatles"],
  ["I Want to Hold Your Hand", "The Beatles"],
  ["She Loves You", "The Beatles"],
  ["Can't Buy Me Love", "The Beatles"],
  ["Eight Days a Week", "The Beatles"],
  ["Ticket to Ride", "The Beatles"],
  ["We Can Work It Out", "The Beatles"],
  ["Paperback Writer", "The Beatles"],
  ["Yellow Submarine", "The Beatles"],
  ["Eleanor Rigby", "The Beatles"],
  ["Penny Lane", "The Beatles"],
  ["Strawberry Fields Forever", "The Beatles"],
  ["All You Need Is Love", "The Beatles"],
  ["Hello, Goodbye", "The Beatles"],
  ["Lady Madonna", "The Beatles"],
  ["Hey Jude", "The Beatles"],
  ["Get Back", "The Beatles"],
  ["The Long and Winding Road", "The Beatles"],
  ["Something", "The Beatles"],
  ["Come Together", "The Beatles"],
  ["Here Comes the Sun", "The Beatles"],
  ["While My Guitar Gently Weeps", "The Beatles"],
  ["Blackbird", "The Beatles"],
  ["Let It Be", "The Beatles"],
  ["Across the Universe", "The Beatles"],
  ["In My Life", "The Beatles"],
  ["Norwegian Wood (This Bird Has Flown)", "The Beatles"],
  ["Yesterday", "The Beatles"],
  ["Michelle", "The Beatles"],
  ["And I Love Her", "The Beatles"],
  ["If I Fell", "The Beatles"],
  ["I Saw Her Standing There", "The Beatles"],
  ["Twist and Shout", "The Beatles"],
  ["Love Me Do", "The Beatles"],
  ["Please Please Me", "The Beatles"],
  ["From Me to You", "The Beatles"],
  ["She Loves You", "The Beatles"],
  ["I Feel Fine", "The Beatles"],
  ["Day Tripper", "The Beatles"],
  ["We Can Work It Out", "The Beatles"],
  ["Paperback Writer", "The Beatles"],
  ["Rain", "The Beatles"],
  ["Lucy in the Sky with Diamonds", "The Beatles"],
  ["A Day in the Life", "The Beatles"],
  ["With a Little Help from My Friends", "The Beatles"],
  ["Sgt. Pepper's Lonely Hearts Club Band", "The Beatles"],
  ["When I'm Sixty-Four", "The Beatles"],
  ["Ob-La-Di, Ob-La-Da", "The Beatles"],
  ["Back in the U.S.S.R.", "The Beatles"],
  ["Dear Prudence", "The Beatles"],
  ["Happiness Is a Warm Gun", "The Beatles"],
  ["Martha My Dear", "The Beatles"],
  ["I'm So Tired", "The Beatles"],
  ["Blackbird", "The Beatles"],
  ["Piggies", "The Beatles"],
  ["Rocky Raccoon", "The Beatles"],
  ["Don't Pass Me By", "The Beatles"],
  ["Why Don't We Do It in the Road?", "The Beatles"],
  ["I Will", "The Beatles"],
  ["Julia", "The Beatles"],
  ["Birthday", "The Beatles"],
  ["Yer Blues", "The Beatles"],
  ["Mother Nature's Son", "The Beatles"],
  ["Everybody's Got Something to Hide Except Me and My Monkey", "The Beatles"],
  ["Sexy Sadie", "The Beatles"],
  ["Helter Skelter", "The Beatles"],
  ["Long, Long, Long", "The Beatles"],
  ["Revolution 1", "The Beatles"],
  ["Honey Pie", "The Beatles"],
  ["Savoy Truffle", "The Beatles"],
  ["Cry Baby Cry", "The Beatles"],
  ["Good Night", "The Beatles"]
].reduce((out, pair) => {
  const title = pair[0];
  const artist = pair[1];
  const key = (title + "|" + artist).toLowerCase();
  if (!out._seen.has(key)) {
    out._seen.add(key);
    out.list.push({
      id: "c" + out.list.length,
      title,
      artist
    });
  }
  return out;
}, { _seen: new Set(), list: [] }).list;
